language: java
os:
    - linux
dist: xenial
sudo: true
env:
    global:
        - TERRAFORM_CMD="$TRAVIS_BUILD_DIR/terraform"
        - QUORUM_CLOUD_TEMPLATES_DIR=quorum-cloud/aws/templates
        - QUORUM_SOCKSPROXY_HOST=localhost
        - QUORUM_SOCKSPROXY_PORT=41232
        # Terraform Variables
        - TF_VAR_region=us-east-1
        - TF_VAR_is_igw_subnets=false
        - TF_VAR_subnet_ids="[\"subnet-4c30c605\",\"subnet-4c30c605\",\"subnet-09263334\",\"subnet-5236300a\"]"
        - TF_VAR_bastion_public_subnet_id="subnet-3a8d8707"
        - TF_VAR_access_bastion_cidr_blocks="[$(dig +short nat.travisci.net | sed -e 's/$/\/32\"/g' | sed -e 's/^/\"/g' | paste -s -d, -)]"
        # - TF_VAR_access_bastion_cidr_blocks="[\"$(curl -s ipecho.net/plain)/32\"]"
        # AWS Configuration
        - secure: "SXNLe/u/hd+PqzLFQ23cwwsXCN14oK3wpubc03MTIJrQwYeJiXin1f9UosvMM1WTS//bHxyTVHF1skWMES82AcCXBJgLzv0K2iymLCuJS7OvQwXdtiiXroxeFUDfbYgfXn6isgASIy74oNcybh5efQThV01S4dOmCkpUwaMfslJtYxReEcm9tvm3+TGKXbO9mN1ulQE0vOcB4EDXZWIvFBamKA+ytGKL1g9z2eBiCzhZdXSkF7u+s1oaBFYVYE5VLiCrBZN7VtGQcjJY3zzbZZUagM140Ip6es7ZKNa9KFlLjPe/fLnLuET/3ybCLoRbiMESwpV2JYefNarivL/zHu2I9KW0X8p+zPFdWXqGUakpaZYPgaTaomyES4e20d/09eNx5swHsTsF8GzSrBlEtC615mOPCWRSs4J8++BO9ry/yVzYpBqo1/g8OFJP6NhIVoPCxJ72KshmanKlmPa6UA7igKh6szeVYgTf7dWmFqhirJw3ovkovhf2gjrWGAAdkA915miGiVIG43nBDRqqzmA6ul6xjWBG81DuHu8VOrOK3C94aalaepwg3Fb1ofcLvS3phj02ovuWL6YwJ6ZUslVpJk8p3ZXJQFAyiO3kWkUL9avTLyVTueyUBNY1Cl0GkuBX7BCReeLgyQy+WZtnxVw0TBJeOVcwYTHGWPQ6zxw="
        - secure: "Lc1lX3K8LEIPX+qzs/UTGn74jEEVop5Pw7zJHsFBUGasW8kY8o94lGN0JNJ9wUFNjxNjkIB/wrIzF4LF+lBTIyINsUONqVHRyDISj5Dlt9Mtig426oiy7USuKgohfp2ub2HV9Jr8xtCCLWExJvT6NRP6c2j28UEYEEPJowV0c5kf0C597gDKrZZ9ZRgK82kQpbG3fM0MnJXUHUt11eeIZofaHyPYJ54fr1u9D5iN8vxUYOv+5XQqRxo1yneyxtNycAIRdh6HLXZeNg5AGUWUQYNpy4FLs8Vz8b+XyIS7r7nrcsLesRIMmbrJQkvWNd7V+4AsBJReD8xHWf7TatRFVTLZTidBO+oflLGkLzVmpxAFv1iUHpudftYy4bZllN+MImK//0EpP0wuj22j6Dkoc+UvanE/KdUPVYp7MM7YW9zRQlY24PlLlxtfdla9bLD1UVA/atThGTyCz44e/GoZaZm+i/SEjUcX4Havk8FJfSJSaZ+MNgeKksJpF/PbFLTQx/IKzUjK46pSYV5nFULE/0UBRx7xinhnHxeb3Rh/hZWjMCqHfK3tbRMvG0Kwx0L/wBv71FIQK50+jjv0J3xfDQgBlePRfnop5YIoUwIdc0y9Kmljb6DP75EkQJ1VFGCt62JwY0HkZIDGKBYflTZh55TcfVHwJXx/M7sXTapSJXk="
        # Github Page configuration to publish test report
        - secure: "nOFXd99M2z+WI4XB0ci0+IIkQvxzZ6ZCJYmkZhp+NrhRkMXy2/LDmDvPwBK2vDLv0GoCL5VPwLEz7mnuU6gOU/HTg+AvNOvm9uElzVlkZvUMHGdRLJm+yagq46BRWe3fkyVyKmj9mjr7dRB6i+sSdk4ntQfoQKmNScebeyQG4Yo851t8lqTpMhTfBN9FazyhOGdoGmYelzQgSgOe3HPbgERvOx/BOZsRzzaKH1n/FhatwLoty7guqnhtfGP9ezOb6sC6XInkZ06SOBDmZeMFUmzy6YLAKN2kdU/wGI8h9DcZQAg2ZrDvUWvR4zU5M0Ehhe9YZqFoW/pupJN45ARTfwUl/F2FRs1UpOWVKy/Ggsy1j5/f1lb0T/7UxGYjsEzEbXTRLS3IMhUZVplNMBdiAfNtmi+nWd05uE0h4OAWIJUqinYnnMkCyZHZaFu2vY5r0+ctBKZgTBbjxt8pP1yzVDwJHBuC0MS4XvfawBs8WDqq7Wr6jeOFUKfN/5CqMdenKFT7Bs1EAPTi/JmJFju8mDRyhrrgiEEe68AwOqkYmv129p4HVi8MC+ZPg6/U8z+zQcPQLYR+YymdAWuJzZa/q5blk65Uf11jBVH07JjqGITwN3TNtde0AbhOFoSrz+CiMxOVx7GHQ3fjk2lMVhGu7u4Xi6a5bCGf0d/AVsfYt2Q="
        - REPO_NAME=jpmorganchase.github.io
        - REPO_OWNER=jpmorganchase
        - GITHUB_USERNAME=quorumbot
addons:
    apt:
        update: true
        packages:
            - dpkg # fixes issue with dpkg-deb error due to travis image issue
            - openssh-client
            - dnsutils
            - maven
            - jq
            - curl
cache:
    directories:
        - $HOME/.m2
before_install:
    - sudo wget https://github.com/ethereum/solidity/releases/download/v0.5.4/solc-static-linux -O /usr/local/bin/solc
    - sudo chmod +x /usr/local/bin/solc
    - wget https://github.com/getgauge/gauge/releases/download/v1.0.4/gauge-1.0.4-linux.x86_64.zip -O gauge.zip -q
    - sudo unzip -o gauge.zip -d /usr/local/bin
    - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip -O terraform.zip -q
    - unzip terraform.zip
    - $TERRAFORM_CMD version
    - git clone https://github.com/jpmorganchase/quorum-cloud.git
install:
    - gauge telemetry off
    - gauge install
matrix:
    include:
        - name: raft
          env:
              - TF_VAR_consensus_mechanism=raft
              - TF_VAR_network_name=ci-${TF_VAR_consensus_mechanism}-${TRAVIS_COMMIT::6}-${TRAVIS_BUILD_NUMBER}
        - name: istanbul
          env:
              - TF_VAR_consensus_mechanism=istanbul
              - TF_VAR_network_name=ci-${TF_VAR_consensus_mechanism}-${TRAVIS_COMMIT::6}-${TRAVIS_BUILD_NUMBER}
before_script:
    - ./src/travis/start_quorum.sh
    - set +e
script:
    - ./src/travis/run_tests.sh
    - set +e
after_script:
    - ./src/travis/stop_quorum.sh
    - set +e
    - ./src/travis/upload_test_report.sh
notifications:
    slack:
        rooms:
            - secure: "C2sbBrFdBIL7kY2j/5pE19/e1QbfMJ58HcN2OhK6+RSGyv08W3UQsCSBPE3SNUmgYPkS5Oo46ikwm0N8CLtapOhc1rdIZV6ikxJQBs5gYUya8+8umlUMCZAV6fRRUxz1KXGMvwfvSmeivWm5oI4iEL6RkM8Sy2LTfLAzqxTCwyx18T4JTvgPyv8pQ+ZGsynQykkBaSFmLS6XQjmMlWOTuMdv7LsLofqn1ivSl7B+kR0eDJggUGGNm/B+JRySuroUo2Cwf9/DdpSCwfs76sEHuXcCeHKmCfkzUVAqve2XBGfsAdPXwvjoGo285e07FraIq2J+4oQSaNyWuExK/RQCNln5zZKNILObEUH7qF/oaJpBt82M0NreaPsczuB98eRvkoM9t5ki3rLk7GKSGL87QraZe1gxZ0TLe/cnb0OsHbhUKnW71WuTS/s+s9vUchCr/Dmer+Cr0sqbS4+cRD4yWAuYEfsAR50yAWymxg0pmRKlffCJpU1pmcEmcOLsnJEdvh8TZu/S9RFoZBPvzQxc+EbifMaY6AWPHT1NmFcXlGzHWrLmj2S/hhngr+rRiqE704pBk/odf7jV3H/P7sPXZPiK4y0+Pj0UvupDeAGUj/Et8Nt3+6VW3OzXgOIrpYCmxlS9GUleecz9JQ/dP513/R3v/GutYNU5P+XRhYMm4EQ="
        on_success: always
        on_failure: always
        on_pull_requests: false
        template:
            - "Build <%{build_url}|#%{build_number}> of %{repository_slug}@%{branch}"
            - "%{result} in %{duration}"
            - "<https://jpmorganchase.github.io/%{repository_name}/docs/html/|Test Specifications>"
            - "Execution reports: <https://jpmorganchase.github.io/%{repository_name}/raft/|Raft> - <https://jpmorganchase.github.io/%{repository_name}/istanbul/|Istanbul>"
