# This is just a sample of how application-local.yml should be:
quorum:
  # This is required only if socks proxy is used
  # Typically when Quorum Network is provisioned with quorum-cloud
  socks-proxy:
    host: localhost
    port: 5000
  # Endpoint to bootstrap a managed Quorum Network providing
  # capabilities to add/remove/stop/start nodes
  # mainly used for advanced test scenarios
  boot-endpoint: http://localhost:8800
  # Metadata about nodes in an existing network
  # mainly used for functional test scenarios
  nodes:
    Node1:
      privacy-address: SXdAvvLuoUY6NO2qSJlr+rAYFa/5PyUD6AZu4lrGqhM=
      url: http://172.31.100.34:22000
    Node2:
      privacy-address: 8jUTuy/Ll8kgptEl0qeJdPAZ4rHC6/X38aJ0/M9Vh0o=
      url: http://172.31.101.63:22000
    Node3:
      privacy-address: 8bPas4ftJullCL3U8y/r9C4XDRzdKhJ0t5rXXVm4/U4=
      url: http://172.31.102.159:22000
    Node4:
      privacy-address: lgDYWZoOPfy3HpPOeGQCaZkd6XmyZxwCGDDDdgZ+Ngg=
      url: http://172.31.101.33:22000
    Node5:
      privacy-address: ioizrAV2KrEMwJfOuKfQJEWuIOc41ZJUvI9QXx64o0M=
      url: http://172.31.101.38:22000
    Node6:
      privacy-address: FULo2nE79tj+EnjvPnnQe9rK44UHZseOERMCDxeXbjs=
      url: http://172.31.102.93:22000
    Node7:
      privacy-address: y+BfCzwQkAisAOz7+UDpyzRYSV9nb1KVDAy9SPgmBhs=
      url: http://172.31.100.127:22000