# This is for 4nodes network provisioned locally using `quorum-cloud/travis/4nodes`
quorum:
  nodes:
    Node1:
      privacy-address: R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=
      url: http://localhost:22000/?PSI=PS1
      third-party-url: http://localhost:9081
      graphql-url: http://localhost:8001/graphql
      psi: PS1
    Node2:
      privacy-address: UfNSeSGySeKg11DVNEnqrUtxYRVor4+CvluI8tVv62Y=
      url: http://localhost:22000/?PSI=PS2
      third-party-url: http://localhost:9081
      graphql-url: http://localhost:8001/graphql
      psi: PS2
    Node3:
      privacy-address: ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc=
      url: http://localhost:22000/?PSI=PS3
      third-party-url: http://localhost:9081
      graphql-url: http://localhost:8001/graphql
      psi: PS3
    Node4:
      privacy-address: oNspPPgszVUFw0qmGFfWwh1uxVUXgvBxleXORHj07g8=
      url: http://localhost:22003
      third-party-url: http://localhost:9084
      graphql-url: http://localhost:8004/graphql

